name: Docker Build

on:
  push:
    branches: [ master, $default-branch ]
  pull_request:
    branches: [ master, $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag rachet-websocket-exchange-rate-staging:web -f docker/php/prod/Dockerfile .
